# Generated by Django 3.2.5 on 2022-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=264)),
                ('lastname', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
                ('subject', models.CharField(max_length=264)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=264, unique=True),
        ),
    ]
