# Generated by Django 3.2.5 on 2022-05-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
